### ISSUE TITLE
SDS011 does not show PM2.5 and PM10 after update to firmware version: NAMF-2020-34

### ISSUE THREAD

**Issue by dpvue** [nettigo/namf#22]
SDS011 does not show PM2.5 and PM10 values after update to firmware version: NAMF-2020-34

**Comment by netmaniac** [comment]
> SDS011 does not show PM2.5 and PM10 values after update to firmware version: NAMF-2020-34

Does powering off sensor for 5 minutes changes anything?

**Comment by dpvue** [comment]
Yes. It's working now! Thanks

**Comment by netmaniac** [comment]
Please reopen if it will happen again.
