### ISSUE TITLE
Device doesn't send mDNS after update to NAMF-2020-37

### ISSUE THREAD

**Issue by bieniu** [nettigo/namf#29]
After updating firmware to `NAMF-2020-37`, the device doesn't send any mDNS information.

**Comment by netmaniac** [comment]
Hi!
I can not reproduce that error. All sensors in my network, after switch to stable still are discovered by avahi-browse -a (tested on Ubuntu). Is there still problem with mDNS in Your sensor?

**Comment by bieniu** [comment]
I've just checked again and this time I can see mDNS packets from the device on the network. Maybe one of my APs is blocking multicast.
