### ISSUE TITLE
Content-Length in POST request not filled

### ISSUE THREAD

**Issue by pkozak2** [nettigo/namf#3]
My custom API (.NET Core) returns 411 HTTP Error.

I found that the Content-Length is not filled in request headers.

Current BETA NAMF-2020-23
![image](https://user-images.githubusercontent.com/9069563/76148158-e8ce6e80-60a3-11ea-9647-3789807e7028.png)

Stable version - NAMF-2019-020:
![image](https://user-images.githubusercontent.com/9069563/76150276-d30f7800-60a8-11ea-900d-fa6996655aa2.png)

Additionaly I found that used Library probably want to fill Content-Length:
[https://github.com/esp8266/Arduino/blob/372a3ec297dfe8501bed1ec4552244695b5e8ced/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp#L673](https://github.com/esp8266/Arduino/blob/372a3ec297dfe8501bed1ec4552244695b5e8ced/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp#L673)

But, not only I have this issue with this library:
[https://github.com/esp8266/Arduino/issues/2678](https://github.com/esp8266/Arduino/issues/2678)

**Comment by pkozak2** [comment]
I tested airohr firmware which using HTTPClient like new nettigo firmware, and it's working with my API, so there is something wrong with new source.
I will try to find what, but I can't promise

**Comment by irukard** [comment]
It's simple. Basic auth isn't working yet.

**Comment by pkozak2** [comment]
Ok, I will try today.

**Comment by netmaniac** [comment]
@irukard I'm not sure if this really BasicAuth issue. It works for me with Influx (so it is not a custom API though), in attached traffic auth headers seems to be exact the same. API responds with 411 not 401, so auth is working. 
I'll take a look at code I guess we are not adding content-length :)

**Comment by netmaniac** [comment]
@pkozak2 I have added Content-Length header when sending. As I thought it was lost when converting code.Try with new FW (2020-24). If it won't work for You reopen issue.

**Comment by pkozak2** [comment]
As Ikurad says, authorization header not working for now.

#4 fixes this issue.
