### ISSUE TITLE
[Feature request] Send device ID via mDNS

### ISSUE THREAD

**Issue by bieniu** [nettigo/namf#31]
Home Assistant uses `zeroconf` to discover a NAM device on the local network and propose a configuration of the integration to the user. The hostname is checked, if it contains `NAM-` that means this is a NAM device.

If the user changes the **network name** in the NAM device configuration, the hostname of the device will also change and the HA will not be able to discover the device.

Adding an additional text `ID` information with the default hostname (`NAM-12345678`) would solve this problem.

This is an example of mDNS information from Shelly device with `ID`:

![image](https://user-images.githubusercontent.com/478555/118471458-10897f80-b708-11eb-8a39-28892f047606.png)

**Comment by netmaniac** [comment]
It should be supported in 38rc6. Code is in beta, so if You want You may test it by building current beta and uploading to sensor. Or wait for next beta release to check. But for me it should work :smiley: 
![Screenshot from 2021-05-17 13-14-04](https://user-images.githubusercontent.com/27457/118479874-d3c28600-b711-11eb-9917-99be88e51b59.png)

**Comment by bieniu** [comment]
Great, I'm using beta to test new features.

**Comment by netmaniac** [comment]
New beta on update server (38rc6)

**Comment by netmaniac** [comment]
Can be done. So, new TXT field with key `manufacturer`, right? Also downcase on ID value is possible. Probably with next beta.

**Comment by bieniu** [comment]
Great, thanks!

**Comment by netmaniac** [comment]
OK, commit 8269356046547bb5f6c296fc0d2ca2287b4063f9 done that. With next beta will be deployed
