### ISSUE TITLE
Disabling "Sent diagnostic data to Nettigo"

### ISSUE THREAD

**Issue by ProBackup-nl** [nettigo/namf#49]
NAMF-2020-41rc4 introduced _opt out for sending diagnostic data to Nettigo_.

Using NAMF-2020-41: Removing the checkmark for "Sent diagnostic data to Nettigo" and choosing "Save and restart"

results in "checkmark" enabled after the page loads again.

Expected is the checkmark to be gone/stay disabled.

**Comment by netmaniac** [comment]
In 43-rc1 should be fixed.
