### ISSUE TITLE
Incorrect data.json structure.

### ISSUE THREAD

**Issue by rbzg** [nettigo/namf#5]
NAMF-2020-26 firmware.
Incorrect data.json structure.
The closing quotation mark after "age" is missing.

`{"software_version": "NAMF-2020-26", "age":"0, "measurements":"3452", "sensordatavalues":[{"value_type":"SDS_P1","value":"5.30"},{"value_type":"SDS_P2","value":"2.40"},{"value_type":"BME280_temperature","value":"23.19"},{"value_type":"BME280_humidity","value":"15.99"},{"value_type":"BME280_pressure","value":"101141.87"},{"value_type":"HECA_temperature","value":"22.18"},{"value_type":"HECA_humidity","value":"18.34"},{"value_type":"samples","value":"195472"},{"value_type":"min_micro","value":"1185"},{"value_type":"max_micro","value":"165036"},{"value_type":"signal","value":"-89"}]}`

**Comment by netmaniac** [comment]
Indeed it was missing. Merged fix and new release was deployed (NAMF-2020-27).
Thank You for contributing,
