### ISSUE TITLE
Switch for Onboard Status LED 

### ISSUE THREAD

**Issue by nonitex** [nettigo/namf#62]
Would be great to have the possibility on the web interface to turn off the LED on the Wemos D1 mini.

As an extra, the switch could be presented on the Home Assistant integration as well.

**Comment by netmaniac** [comment]
Sorry, but it is not possible. NAM is based on Luftdaten (now Sensor Community), so we share pinout. They have selected pins D3/D4 for I2C bus, and LED is on D4. So LED is tied to I2C bus. Without hardware redesign there is no possibility to turn off LED via software.
