### ISSUE TITLE
What is the WiFi password in config mode?

### ISSUE THREAD

**Issue by wooyek** [nettigo/namf#63]
I have tried the `nettigo123` password to authenticate while connecting to sensor WiFi but it does not work [the docs](https://air.nettigo.pl/baza-wiedzy/namf-konfiguracja-firmware/) does not provide other password :(

**Comment by netmaniac** [comment]
Password is `nettigo.pl` Docs site is being moved to https://docs.nettigo.pl/pl/spis and being updated.
