### ISSUE TITLE
NAM KIT loses BME280 and HECA data

### ISSUE THREAD

**Issue by DaleBCooper** [nettigo/namf#68]
Today was the 3rd time in the last two weeks one of my NAM Kits (BME 0.3.3 PRO soldered) lost the BME280 and HECA data.
The PM data from the SDS011 was not effected.
I have no idea what may have caused this.
After a reboot via the web interface the HECA and BME280 worked again.

One annoying side effect is that the graphs for temperature, humidity and pressure get distorted, especially on opensensemap.org and aqi.eco since the firmware sends the following values to the API:

temperature: -128
pressure: -1
humidity: -1

Wouldn't it be better to send an empty string "" in such cases to all API to at least prevent the distortion of the graphs?

![Screenshot 2023-07-14 at 02-41-21 Temperature _ Humidity _ Pressure - Dashboards - Grafana](https://github.com/nettigo/namf/assets/9580059/f2001399-0856-4e75-9ab8-bc1b6c1e21e2)
![Screenshot 2023-07-13 at 21-33-01 Sensor status_](https://github.com/nettigo/namf/assets/9580059/d5da71fd-1865-49a9-91aa-ea31bd86c56d)
![Screenshot 2023-07-13 at 21-32-08 Current data_](https://github.com/nettigo/namf/assets/9580059/bc07e864-8be8-4245-b3b0-49580ca35818)

**Comment by netmaniac** [comment]
OK, with 46rc3 it should not happen again. If this is still problem you need to switch to beta updates channel to get 46rc3. Or wait for regular -46 release.
