### ISSUE TITLE
[feature] Read BH1750FVI I2C sensor /  SEN-2096 

### ISSUE THREAD

**Issue by repcio** [nettigo/namf#73]
It would be good if data from sensors BH1750FVI (Nettigo ID: SEN-2096) could be read.

**Comment by netmaniac** [comment]
NAMF-2020-46rc5 (beta update channel) has support for BH1750. Feature is not complete yet, but basic stuff works.

**Comment by repcio** [comment]
Thank you !
It works, now I need to adjust sensor instalation place.

**Comment by netmaniac** [comment]
Support for BH750 is in stable version since NAMF-2020-46
