### ISSUE TITLE
InfluxDB upload doesn't use configured password

### ISSUE THREAD

**Issue by repcio** [nettigo/namf#74]
When sending data to InfluxDB only username is used so no data is placed in the database when username and password is required to upload data.

**Comment by netmaniac** [comment]
There is new release in beta channel, should use user/password set in config, however I don't have currently access to influx to test it.

**Comment by repcio** [comment]
I will check this in next 2 weeks as I have downgraded InfluxDB server to gather data.

**Comment by netmaniac** [comment]
I have now released NAMF-2020-46rc8 and it has finall fix for password auth in Influx 1.x (2.x API is not yet supported). From this release it works for me.
